# Generated by Django 5.0.3 on 2024-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='موجود بودن محصول'),
        ),
    ]
