# Generated by Django 5.0.3 on 2024-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=30, null=True, verbose_name='عکس کاربر'),
        ),
    ]
